// Run after npm run build: npx electron scripts/mobile-smoke.cjs
// Uses an isolated profile; never signs in or starts a public service.
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const assert=require('node:assert/strict');
// Isolate the smoke server from an operator's active mobile connection.
const http=require('node:http');
const originalListen=http.Server.prototype.listen;
http.Server.prototype.listen=function(...args){if(args[0]===8082)args[0]=0;return originalListen.apply(this,args)};
const root=path.resolve(__dirname,'..');
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'trilorah-mobile-smoke-'));
app.setPath('userData',profile);
app.setAppPath(root);
process.env.NODE_ENV='test';
delete process.env.DESIGN_MODE;
app.on('browser-window-created',(_,win)=>win.hide());
const errors=[];
app.on('web-contents-created',(_,contents)=>contents.on('console-message',(_event,level,message)=>{if(level>=3)errors.push(message)}));
require('../dist-electron/main.js');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<70;i++){const v=await fn();if(v)return v;await wait(150)}throw Error('Timed out waiting for UI');}
async function run(){
 await app.whenReady();
 const desktop=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/index.html')));
 const js=code=>desktop.webContents.executeJavaScript(code);
 await until(()=>js('!!window.api && !!document.getElementById("root")?.firstElementChild').catch(()=>false));
 await js('window.api.mobileEnable(true)');
 const mobileStatus=await js('window.api.mobileStatus()');
 const base=`http://127.0.0.1:${mobileStatus.port}`;
 await js('window.api.openOutput()');
 const output=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('output.html')));
 const code=await js('window.api.mobileCode(true)');
 const remote=new BrowserWindow({show:false,width:390,height:844,webPreferences:{contextIsolation:true,nodeIntegration:false,offscreen:true,backgroundThrottling:false}});
 await remote.loadURL(base+'/remote');
 const phone=code=>remote.webContents.executeJavaScript(code);
 await phone(`document.getElementById('code').value=${JSON.stringify(code.code)};document.getElementById('pairButton').click()`);
 const pending=await until(async()=>{const s=await js('window.api.mobileStatus()');return s.pending[0]});
 await js(`window.api.mobileApprove(${JSON.stringify(pending.id)},true)`);
 await until(()=>phone('document.getElementById("connection").textContent === "connected"'));
 await until(()=>phone('document.getElementById("version").options.length > 0'));
 // Scripture search lives behind the search key in the dock; Enter sends it straight up.
 await phone('document.getElementById("searchOpen").click()');
 assert.equal(await phone('document.getElementById("searchDock").classList.contains("searching")'),true);
 await phone('document.getElementById("reference").value="John 3:16";document.getElementById("loadVerse").click()');
 await until(()=>phone('document.getElementById("liveLabel").textContent.includes("John 3:16")'));
 await until(()=>phone('document.getElementById("liveStatus").textContent === "on screen"'));
 assert.equal(await phone('document.getElementById("searchDock").classList.contains("searching")'),false,'search closes once the verse is up');
 // Nothing is waiting, so go live is refused rather than silently doing something else.
 assert.equal(await phone('document.getElementById("goLive").getAttribute("aria-disabled")'),'true');
 await phone('document.getElementById("next").click()');
 await until(()=>phone('document.getElementById("liveLabel").textContent.includes("John 3:17")'));
 assert.equal(await phone('document.querySelectorAll("[data-tab]").length'),3);
 await phone('document.getElementById("searchOpen").click()');
 await phone('document.getElementById("reference").value="John 3:";document.getElementById("reference").dispatchEvent(new Event("input"))');
 await until(()=>phone('document.querySelectorAll("#suggestions .sugg").length>0'));
 assert.ok((await phone('document.getElementById("suggestions").innerText')).includes('John 3:1'));
 await phone('document.getElementById("reference").dispatchEvent(new KeyboardEvent("keydown",{key:"Escape"}))');
 await phone('document.getElementById("searchClose").click()');
 // The host must continue responding while another desktop tab is visible.
 await js('[...document.querySelectorAll("nav button")].find(b=>b.textContent.toLowerCase().includes("settings"))?.click()');
 await phone('document.querySelector("[data-tab=songs]").click()');
 await until(()=>phone('document.querySelectorAll("#songList .row").length>0'));
 await phone('document.querySelector("#songList .row").click()');
 await until(()=>phone('document.querySelectorAll("#songSections .lyric-main").length>0'));
 await phone('document.querySelector("#songSections .lyric-main").click()');
 await until(()=>phone('document.getElementById("readyLabel").textContent.includes("·") && !document.getElementById("ready").hidden'));
 await until(()=>phone('document.getElementById("goLive").getAttribute("aria-disabled") === "false"'));
 await phone('document.getElementById("goLive").click()');
 await until(()=>phone('document.getElementById("liveLabel").textContent.includes("·") && document.querySelector("#songSections .lyric.is-live") !== null'));
 const current=await js('window.api.getLiveContent()');
 assert.equal(current.kind,'song');assert.ok(current.lines.length);
 await until(()=>output.webContents.executeJavaScript(`document.body.innerText.includes(${JSON.stringify(current.lines[0])})`));
 const token=await phone('localStorage.getItem("trilorah.remote.token")');
 const command=async(command,args={})=>{
   const res=await fetch(base+'/api/command',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({command,args})});
   const data=await res.json();assert.equal(res.status,200,JSON.stringify(data));return data.result;
 };
 await command('screen',{value:'black'});assert.equal(await js('window.api.getScreenState()'),'black');
 await command('screen',{value:'live'});
 await command('step',{delta:1});
 await command('theme',{key:'safeMargin',value:9});assert.equal(await js('window.api.getSetting("safeMargin")'),9);
 await command('alert',{text:'Mobile smoke test'});assert.equal((await js('window.api.getAlert()')).text,'Mobile smoke test');
 await command('alert',{dismiss:true});
 const timer=await command('timer',{action:'create',name:'Test timer',seconds:60});assert.ok(timer.id);
 await command('timer',{action:'start',id:timer.id});await command('timer',{action:'pause',id:timer.id});
 const slidePath=path.join(profile,'slide.svg');fs.writeFileSync(slidePath,'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#263d31"/><text x="60" y="190" fill="white" font-size="48">Welcome to church</text></svg>');
 await js(`window.api.savePresentations([{id:'test-deck',title:'Welcome',slides:[${JSON.stringify(slidePath)}]}])`);
 await command('deck',{id:'test-deck',index:0});await wait(100);await command('live',{id:(await command('state')).preview.id});
 assert.ok((await command('thumbnail',{target:'live'})).startsWith('data:image/'));
 await js('window.api.setSetting("publicWebUrl","https://example.com")');await js('window.api.setSetting("accountSlug","test-church")');
 await command('qr');await wait(100);assert.equal((await command('state')).live.label,'Congregation QR');
 await command('verse',{reference:'John 3:16',version:'KJV'});
 await remote.webContents.executeJavaScript('document.querySelector("[data-tab=verses]").click()');
 await phone('window.scrollTo(0,0)');
 await wait(1200);
 remote.showInactive();await wait(500);
 const image=await remote.webContents.capturePage();remote.hide();assert.equal(image.isEmpty(),false,'Phone screenshot must contain rendered pixels');
 const screenshot=path.join(profile,'mobile-remote.png');fs.writeFileSync(screenshot,image.toPNG());
 const state=await js('window.api.mobileStatus()');await js(`window.api.mobileRevoke(${JSON.stringify(state.devices[0].deviceId)})`);
 await until(()=>phone('!document.getElementById("pair").hidden && document.getElementById("app").hidden'));
 await js('window.api.mobileEnable(false)');
 const relevantErrors=errors.filter(e=>!e.includes('Content Security Policy')&&!e.includes('ERR_FILE_NOT_FOUND'));
 if (relevantErrors.length) console.error("RELEVANT_ERRORS", JSON.stringify(relevantErrors, null, 1)); assert.deepEqual(relevantErrors,[]);
 console.log('MOBILE_SMOKE_PASS '+JSON.stringify({screenshot,checks:['pair approval','scripture search/live','next verse','go live refused when nothing is ready','control with desktop Settings open','song ready → go live','screen black/restore','theme','message','timers','revoke'],errors}));
 app.exit(0);
}
run().catch(e=>{console.error('MOBILE_SMOKE_FAIL',e);app.exit(1)});
setTimeout(()=>{console.error('MOBILE_SMOKE_FAIL overall timeout');app.exit(1)},60000).unref();
